### ISSUE TITLE
Sort by ES hits per concept / PITs per concept

### ISSUE THREAD

**Issue by bertspaan** [histograph/neo4j-plugin#9] opened 2015-11-02 09:56 UTC
Sort by ES hits per concept / PITs per concept.

(Or, even better: sort by ES hits \* ES score per concept / PITs per concept: #10)

**Comment by jobspierings** [comment] 2016-01-19 13:00
@bertspaan compare this one w/ #10 and [API #21](https://github.com/histograph/api/issues/21) - is this related to any specific user request/bug? 

If not we can close this for now, and reopen if neccessary. If best solution for sorting results is clear please advice.

**Comment by bertspaan** [comment] 2016-01-19 13:21
Please leave open. This seems still to be best solution. Why this urge to close as many issues as possible?

**Comment by sbocconi** [comment] 2016-03-14 16:45
Can I close this as duplicate of #10 which is better explained?

**Comment by bertspaan** [comment] 2016-03-14 17:12
Ok!

**Comment by sbocconi** [comment] 2016-03-14 17:36
Duplicates #10

**Closed as completed by sbocconi** 2016-03-14 17:36 UTC
Labels: duplicate, enhancement
